---
title: "My Resume"
output:
  html_document:
    toc: true
    toc_float: true
    theme: cerulean
---

# Education
**COLUMBIA UNIVERSITY MAILMAN SCHOOL OF PUBLIC HEALTH, NEW YORK, NY**

Master of Science in Biostatistics, June 2025 (expected)  

**UNIVERSITY OF CALIFORNIA, SAN DIEGO, LA JOLLA, CA**

Bachelor of Science in Global Health, August 2022  

**SAN DIEGO MESA COLLEGE, SAN DIEGO, CA**

Associate of Science in Biology, June 2020

# Experience

**SAFE HARBOR HOME CARE**

Certified Nursing Assistant, December 2022 – June 2023

* Assist with the activities of daily living and personal care, including:
*	Bathing, shaving, ambulation 
*	mouth care, dressing, exercising 
*	hair care, feeding, toileting/incontinence care 
*	nail care, positioning, medication reminding
*	Skincare, transferring, meal planning & preparation


**SAFE HARBOR HOME CARE**

Caregiver, July 2022 – October 2022

*	Assist with the activities of daily living and personal care, including:
*	Bathing, shaving, ambulation 
*	Mouth care, dressing, exercising 
*	Hair care, feeding, toileting/incontinence care 
*	Nail care, positioning, medication reminding
*	Skincare, transferring, meal planning & preparation


**HEALTH FRONTIERS IN TIJUANA** 

Undergraduate Internship, April 2022 – July 2022

*	Registering patients in the Electronic Medical Record
*	Managing patient records
*	Soliciting patients’ Chief Complaint
*	Assisting in vitals measurements
*	Shadowing consultations


**UNIVERSITY OF CALIFORNIA, SAN DIEGO**

Migrant Shelter Clinic Volunteer, October 2021-December 2021

*	Conduct a COVID medical screening and a general medical screening
*	Supporting the medical staff by taking temperatures, collecting COVID tests, delivering to the lab
*	Establishing labels and screening charts, and recording data into electronic medical record system
*	Facilitating with the medical team to follow up with any medical concerns.

**CHILD FAMILY HEALTH INTERNATIONAL**

Virtual Global & Public Health Internship - Bolivia, August 2021 – September 2021

*	Competency-informed readings and content
*	Intercultural training 
*	30 hours of Spanish learning
*	Global seminars on health topics with experts in local health systems and culture
*	Virtual visit of local hospitals and case studies discussions
*	Group project of designing health posters and lectures for local health education

**MARINE CORPS RECRUIT DEPOT, San Diego, CA**

Phlebotomist Externship, May 2021-June 2021

*	Identifying patients via ID, medical record, or other means
*	Drawing blood using needles and other equipment
*	Labeling samples correctly and sending them for testing 

**FOUNDATION FOR INTRNATIONAL MEDICAL RELIEF OF CHILDREN**

Virtual Global Health Fellowship, April 2021 – May 2021

*	Exploration of global health topics 
*	Readings on relevant subjects in global health, prevalent disease, and sustainable development
*	Training led by healthcare professionals and field staff with experience in global health 
*	Case study discussions led by medical professionals
*	Virtual clinical observation 

# Certificate
* Certified Phlebotomy Technician (CPT I) Certificate 
* Certified Nursing Assistant (CNA)

# Skills
* Microsoft Word, Excel, PowerPoint
* R
